### ISSUE TITLE
Is there any example of this project?

### ISSUE THREAD

**Issue by gardenia22** [k2kobayashi/sprocket#103]
I tried to run this project on vcc2016 dataset but didn't get any impressive result. Could you please share some examples of the result?

**Comment by k2kobayashi** [comment]
Hi, I upload some conversion samples in temporal place.
https://www.dropbox.com/sh/27p1cy4i4rsy8yc/AAAzK6wUlaORxmrTO8hHo5D0a?dl=0

**Comment by gardenia22** [comment]
@k2kobayashi Thank you so much for sharing! Are there any parameters need to be tuned except for minf0 and maxf0? Are those results are out of training sample?

**Comment by k2kobayashi** [comment]
Yes. These samples are open samples. 
Actually, I tuned power threshold parameter in each speaker-dependent YAML file as follows: https://www.dropbox.com/sh/0ee91jvv28cuhpb/AACxlQ62AgbhcDsRXHEQRkIHa?dl=0
Power threshold parameter can tune by following npow histogram, can be got current master as the similar manner of F0 range setting.

**Comment by gardenia22** [comment]
@k2kobayashi Thanks a lot for sharing those configure files. I usually encounter following convergence warning, is it normal:
```
/py3/lib/python3.6/site-packages/sklearn/mixture/base.py:237: ConvergenceWarning: Initialization 1 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  % (init + 1), ConvergenceWarning)
```

**Comment by k2kobayashi** [comment]
It's a warning to notify the likelihood increase of GMM training is still bigger than the threshold of sklearn default setup when the final iteration of GMM training. That's not a big problem as usual.
If you want to avoid this warning, you try to increase the number of iteration or decrease the number of mixture component.

**Comment by gardenia22** [comment]
@k2kobayashi I also often get the following error during the "extract acoustic features" stage:

```
python(75968,0x7fff7c0ac300) malloc: *** error for object 0x7fe3e1485008: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

Then I run again, it will continue but will get the same error sometime later.

**Comment by gardenia22** [comment]
Sorry for close the reopen the issue, it was an unintentional misoperation

**Comment by ahujaofficial** [comment]
@k2kobayashi  , these dropbox links are not working for me. i also have same issue of how to tune parameters other than min and max f0 since output quality is not good for me. and which all parameters to tune other than  min and max f0.

**Comment by lgommans** [comment]
The samples link in the readme is dead, the links above are dead... it has only been a few years!

If someone can pass me any samples I could host them in a more durable place. (I've been having issues with people using free file sharing services since I was a teen; now, ~13 years later, the forum where I was active is dead but the tutorial files which I re-hosted are still available! I won't promise it'll still work in 2100, but let's say at least a decade...)

**Comment by k2kobayashi** [comment]
Sorry for inconvinience. I modified URL again.
