### ISSUE TITLE
The example's convert.py doesn't convert aperiodicity. Is this your intention?

### ISSUE THREAD

**Issue by Hiroshiba** [k2kobayashi/sprocket#107]
Here, converted aperiodicity is calculated, but this value is not used below.
https://github.com/k2kobayashi/sprocket/blob/8d68cb43edda887982e36ba363df020406afdbf5/example/src/convert.py#L138

Is this your intention?

**Comment by k2kobayashi** [comment]
Hi @Hiroshiba,
Thanks for the issue. This function is actually redundant because conversion of codeap is not fully implemented correctly. I will temporally remove this function. And it is going to be implemented the codeap conversion.
