### ISSUE TITLE
run_sprocket.py throws error

### ISSUE THREAD

**Issue by vivek-sethia** [k2kobayashi/sprocket#108]
Can you help me with this error? I have followed the steps for VC:

This commands throughs an error for me:

`### 4. Train GMM and converted GV ###
Traceback (most recent call last):
  File "run_sprocket.py", line 153, in <module>
    str(PAIR_DIR))
  File "/home/../../src/train_GMM.py", line 87, in main
    jnth5 = HDF5(jntf, mode='r')
  File "/home/../anaconda3/lib/python3.6/site-packages/sprocket_vc-0.18-py3.6.egg/sprocket/util/hdf5.py", line 47, in __init__
    "h5 file does not exist in " + self.fpath)
FileNotFoundError: h5 file does not exist in data/pair/SF1-TF1/jnt/it4_jnt.h5`

**Comment by vivek-sethia** [comment]
@k2kobayashi Let me know where I might be wrong

**Comment by malayaleecoder** [comment]
@k2kobayashi I am faced with the same error. Please let us know the fix. Cheers

**Comment by k2kobayashi** [comment]
Hi @vivek-sethia and @malayaleecoder,
Thank you for notifying me and sorry for the serious bug.
I have modified and pushed it.
Could you pull the current master and run sprocket again?

**Comment by malayaleecoder** [comment]
@k2kobayashi Thanks for the patch, it's all good now.

**Comment by vivek-sethia** [comment]
@k2kobayashi Thank you its working. I will close this issue now.
