### ISSUE TITLE
I can't run DIFFVC with 'F0 transform'

### ISSUE THREAD

**Issue by Hiroshiba** [k2kobayashi/sprocket#110]
In `vc_example.md`, how to run DIFFVC with `F0 transform` is explained like this.
```
By running "run_sprocket.py" while using these speech samples as a new source speaker (i.e., "SF1_1.02"), you can build the vocoder-free VC system and generate the converted speech samples.
```

So I tried run codes like this.
```bash
python initialize.py -1 SRC TAR
python initialize.py -2 SRC TAR
python initialize.py -3 SRC TAR

python run_f0_transformation.py SRC TAR
F0RATIO=1.00  # example

python run_sprocket.py -1 -2 -3 -4 -5 SRC_${F0RATIO} TAR}
```

Then error is occurred, "./list/SRC_1.00_train.list is not found."

Maybe, the steps `initialize.py -> run_f0_transformation.py -> run_sprocket.py` are incorrect.
In my opinion, the steps `initialize.py -> run_f0_transformation.py -> initialize.py -> run_sprocket.py` are correct.

Is my understanding correct?

**Comment by k2kobayashi** [comment]
Hi @Hiroshiba. 
You are exactly true. It requires initialization process between F0 transformed source and target speakers because some configuration files such as speaker yml and pair yml files are not automatically generated via ```run_f0_transformation.py```.
I make that description much easy to understand.
