### ISSUE TITLE
ownershipの移行

### ISSUE THREAD

**Issue by k2kobayashi** [k2kobayashi/sprocket#83]
本日中に，ownershipをk2kobayashiに移行して，publicする予定です．

**Comment by k2kobayashi** [comment]
publicにしてからownershipを移行しました．晴れてコードが公開されました，
これまでご協力ありがとうございました．また今後共よろしくお願いします．

**Comment by k2kobayashi** [comment]
告知等は，後日実施する予定です．

**Comment by tats-u** [comment]
assignされたのですが何をすればいいですか？

**Comment by k2kobayashi** [comment]
ただの通知なので特にやることはないです．クローズしますね．
