### ISSUE TITLE
Drop Python 2 Support

### ISSUE THREAD

**Issue by k2kobayashi** [k2kobayashi/sprocket#84]
Python3のみをサポートする仕様に変更する．

**Comment by tats-u** [comment]
サポートする最低バージョンはいくつにしましょうか？個人的には3.5か3.6推しですが。

**Comment by k2kobayashi** [comment]
3.5以降で良いと思います．
@演算子の方が見やすいかもしれませんが，可読性はどうかなと思います．
（先程まで＠演算子を知りませんでした．）

**Comment by tats-u** [comment]
`np.dot`よりは見やすくなると思います。
